/**:
  ros__parameters:
    wheel_radius: 0.363 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.225 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.98 # between front wheel center and rear wheel center
    wheel_tread: 1.61 # between left wheel center and right wheel center
    front_overhang: 0.865 # between front wheel center and vehicle front
    rear_overhang: 0.865 # between rear wheel center and vehicle rear
    left_overhang: 0.134 # between left wheel center and vehicle left
    right_overhang: 0.134 # between right wheel center and vehicle right
    vehicle_height: 1.62
    max_steer_angle: 0.56 # [rad]
